### ISSUE TITLE
Move this repository to NationalGenomicsInfrastructure org

### ISSUE THREAD

**Issue by remiolsen** [NationalGenomicsInfrastructure/anglerfish#69]
This project has outgrown me as single developer. 

I feel like the NGI github organisation should be it's home. @alneberg or @kedhammar, what do you think?

**Comment by kedhammar** [comment]
It could be nice to have an NGI repo as the upstream for deployments, but I don't have any strong feelings on the matter :)

**Comment by alneberg** [comment]
Sure, feel free to move it if you want to.
